webpack-contrib/webpack-bundle-analyzer

- src/BundleAnalyzerPlugin.js
If you run webpack not directly but through a wrapper (like grunt-webpack) then using `setTimeout` generates race conditions: sometimes grunt is killing webpack thinking that everything went good and bundle-analyze is not firing at all.
Changing that to `setImmediate` fixes the problem and still placing all the logs to the bottom
> setTimeout -> setImmediate

- src/analyzer.js
So, I'm not really sure why there are stats files the are `children` only, but I'm finding the that my stats bundle has `assets` and `children`. I've a large setup including CSS Modules with ExtractTextPlugin. 
When using the CLI, I had this problem:
```
Could't find any javascript bundles in provided stats file
```
Summary of my stats file
```
{
"errors": [],
"warnings": [],
"version": "1.13.2",
"hash": "blah",
"time": 1000,
"publicPath": "/assets/",
"assetsByChunkName": {
.. omitted ..
},
"assets": [
{
"name": "vendor.js",
.. omitted ..
},
]
"children": [
"errors": [],
"warnings": [],
"publicPath": "/assets/",
"assetsByChunkName": {},
"assets": [],
"chunks": [
{
"id": 0,
"rendered": true,
"initial": true,
"entry": true,
"extraAsync": false,
"size": 2210,
"names": [],
"files": [ …
```
> Only check children if assets is empty

- README.md
- src/BundleAnalyzerPlugin.js
- src/viewer.js
Allows to set different bind host for Analyzer server.
Example use is when Analyzer is running inside Docker container with Virtualbox.
This setup requires to access running applications on different ip than localhost. So we need have way how make Analyzer server listen on `http://192.168.0.99:8888` or similar.
> Ability to set host address where HTTP server should listen

- README.md
To avoid issues like #47 in the future, it might be a good idea to document this PowerShell weirdness as described by @SukantGujar in https://github.com/th0r/webpack-bundle-analyzer/issues/47#issuecomment-279600901
What do you think?
> Add PowerShell specific stats.json generation instructions

- src/bin/analyzer.js
Adds the option to customize the _host_ when running CLI in _server_ mode.
The `host` option defaults to `0.0.0.0`.
> Add server host name option to CLI

- src/viewer.js
When using a port value of `0` (or if omitting the port argument) `httpServer` will assign a random port ([documentation](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)).
Sadly `webpack-bundle-analyzer` will still advertise the port `0` and not the random one making the webserver impossible to find.
This patch simply change the url calculation by using `server.address().port` to retrieve the used port.
> Correctly advertise port when using a random one

- src/parseUtils.js
- test/bundles/validBundleWithArrowFunction.js
- test/bundles/validBundleWithArrowFunction.modules.json
When using e.g. [uglifyjs](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) with options ```{uglifyOptions: { ecma: 8 }}``` bundles with arrow functions are generated. This caused the analyser to always use ```stats``` over ```parsed``` and ```gzipped``` because it could not parse the bundles.
I don't know what's necessary to properly support this, but with this fix my project works nicely.
> Allow webpack modules to be wrapped in arrow functions.

- .travis.yml
- README.md
- package.json
- Updates repo URLs in `package.json`
- Updates `travis.yml` to only build PR's + master
> chore: Update repo URLs

- package.json
- yarn.lock
Closes #130. 
Bumping `ws` dependency to a new major version should not affect our code. https://github.com/websockets/ws/releases/tag/3.0.0
> Bump ws dependency to ^3.3.1 to fix DoS vulnerability

- README.md
I took https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v3.0.2/README.md as an example of the README.md structure.
See the rendered version here: https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/readme-webpack-contrib/README.md
> Update README.md to match webpack-contrib style

- .travis.yml
- CHANGELOG.md
- package.json
- src/viewer.js
- test/viewer.js
- yarn.lock
This prevents the process from exiting when an `'error'` event is emitted on the WebSocket server client.
Refs: https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/138
> Add a listener for the 'error' event on the WebSocket server client

- package.json
- src/BundleAnalyzerPlugin.js
- yarn.lock
Fixes #119 
I've seen this problem appear in the logs as:
```
fs.writeFileSync(statsFilepath, JSON.stringify(stats, null, 2));
RangeError: Invalid string length
```
The problem is that we're trying to serialize the whole stats object into JSON at once, which causes memory issues with larger projects. The stats object has a shape including `{"assets": [...], "entrypoints": {...}, "chunks": [...], "modules": [...]}` and it's the `chunks` and `modules` fields that are really large lists.
~~To fix this I imported JSONStream and paired it with a writable stream to serialize and flush each key on it's own. For larger projects we might need to go further and iterate/write each item within the chunks/modules/children keys individually.~~
> Output large json stats objects

- gulpfile.js
- package.json
- yarn.lock
[This workaround](https://github.com/webpack-contrib/webpack-bundle-analyzer/compare/simplify-gulp-tasks?expand=1#diff-b9e12334e9eafd8341a6107dd98510c9R28) can be removed after https://github.com/gulpjs/glob-watcher/pull/34 is merged.
> Simplify gulp tasks

- CONTRIBUTING.md
I think there's been some time since `dev` branch was last present. Nowadays pull requests should be done against the `master` branch.
Do I remember things correctly, @th0r? We no longer use `dev` branch in this repository, right?
> Update CONTRIBUTING.md to refer to master branch, not dev

- CHANGELOG.md
- src/BundleAnalyzerPlugin.js
Fix #154 according to @sokra suggestion
> Fix webpack 4 warning

- CHANGELOG.md
- src/parseUtils.js
- test/bundles/validWebpack4Chunk.js
- test/bundles/validWebpack4Chunk.modules.json
- test/bundles/validWebpack4ChunkAndEntryPoint.js
- test/bundles/validWebpack4ChunkAndEntryPoint.modules.json
Webpack 4 has a new chunk loading style, looking something like this:
```js
(window.webpackJsonp=window.webpackJsonp||[]).push([[27],{"57iH":function(e,n,t){console.log("hello world")}}]);
```
WDYT to this approach?
> Fix parsing webpack 4's chunks

- src/analyzer.js
- test/analyzer.js
- test/stats/with-modules-in-chunks/expected-chart-data.js
- test/stats/with-modules-in-chunks/stats.json
> Collect modules from `chunks` array

- src/analyzer.js
- test/analyzer.js
- test/stats/with-missing-parsed-module/bundle.js
- test/stats/with-missing-parsed-module/stats.json
Fixes https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/171#issuecomment-388515342
> Filter out modules that are not part of parsed bundle

- src/parseUtils.js
- test/bundles/validWebpack4AsyncChunkWithOptimizedModulesArray.js
- test/bundles/validWebpack4AsyncChunkWithOptimizedModulesArray.modules.json
> Refactor parsing logic

- client/viewer.jsx
- src/viewer.js
- views/viewer.ejs
> Disable viewer websocket connection if mode is static

- README.md
Update information that plugin provides `parsed` and `gzip` size values only if files actually exist in the file system.
Closes #191
> Update README.md (#191)

- src/BundleAnalyzerPlugin.js
- src/viewer.js
Fixes #232 by prolonging webpack's "done" hook until analyzer finishes writing report / stat files.
> Make webpack's done hook wait until analyzer writes report / stat file.

- CHANGELOG.md
This release would contain these pull requests:
* https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/222
* https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/227
* https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/231
* https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/234
* https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/247
I think this would mean a patch version bump. I could release a new version with these pull requests if that's OK to you, @th0r?
> Prepare next release

- package-lock.json
- package.json
- src/parseUtils.js
Fixes #245
Supporting both acorn 5 and acorn 6 is not feasible because `acorn-walk` got split into its own module.
> Update acorn to version 6

- client/components/ModulesTreemap.jsx
- client/components/Tooltip.jsx
`x` and `y` coordinates of the FoamTree [click event](https://get.carrotsearch.com/foamtree/demo/api/index.html#event-details) are relative to the visualization container element so we can't rely on them when sidebar is pinned.
> Fix positioning of the context menu when sidebar is pinned

- src/bin/analyzer.js
Fixes https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/239
> Fix showing help message on `-h`

- CHANGELOG.md
- src/viewer.js
- views/script.ejs
- views/viewer.ejs
Don't let `</script>` in `chartData` or in internal assets break the page.
Vulnerability details: https://blog.uploadcare.com/vulnerability-in-html-design-the-script-tag-33d24642359e
> Properly escape embedded JS/JSON

- CHANGELOG.md
- src/viewer.js
- views/script.ejs
Closes https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/254
> Use relative links for serving internal assets

- src/viewer.js
- views/script.ejs
- views/viewer.ejs
Fixes https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/263
> Fix regression with escaping internal assets

- .browserslistrc
- package-lock.json
- package.json
- webpack.config.js
This adds [`autoprefixer`](https://github.com/postcss/autoprefixer) for CSS prefixing. (Which is a follow-up re: PR review feedback in https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/246#discussion_r272921108 / #255).
As part of making this change, I moved the [browserslist](https://github.com/browserslist/browserslist) config that was specified inline in the Webpack config out to a `.browserslistrc` file (it could just as well be added as a `browserslist` key to `package.json` -- could go either way on that personally), so that the same browser list will be used by `babel-preset-env` and `autoprefixer` / other `postcss` plugins.
This build config change currently only results in a tiny difference to the generated browser JS bundle: it adds prefixes to the two places …
> Add CSS autoprefixer (resolves #255)

- src/BundleAnalyzerPlugin.js
- Detect `AsyncMFS` to support dev-server of Nuxt 2.5 and above
- #274
> Add AsyncMFS for getBundleDirFromCompiler

- src/BundleAnalyzerPlugin.js
fix #292. But I need some help about testing these change.
> fix: call stats.toJson on each time to avoid the stats mutation

- README.md
- src/BundleAnalyzerPlugin.js
- src/bin/analyzer.js
It's a single line of quite self-explanatory code. But I'm happy to write tests, just not sure where.
The logic I went with was, if analyzer port is specified, (and) if it is 'auto' use 0, else use the specified value. If it is not specified, use 8888, the default.
Closes #281
> Add support for 'auto' option with analyzer port #281

- src/BundleAnalyzerPlugin.js
add a default value for BundleAnalyzerPlugin's options
fixes #300
> fix: solved the error — options is required

- CHANGELOG.md
- client/components/CheckboxList.jsx
Fixes #316
The relevant piece of state here is derived from props, and was failing to update upon prop update in the particular case noted in #316.
One thought re: preventing this class of bug in future is to centralize the state management logic that handles whether all bundles are showing, putting it in the shared MobX store (and eliminating use of state derived from props). I might have time to explore this in a separate PR, but I think this quick fix is probably better for now.
Because the `componentWillReceiveProps` handler appears to have been added for <a href="https://github.com/bregenspan/webpack-bundle-analyzer/commit/279bb2638f1cddf04b319966c71565c48d874f3a">`webpack --watch`</a> support, I tested that the watch mode/dev server compatibility still functions as expected after …
> Fix case where checked bundles in sidebar don't update

- client/components/Tooltip.css
- client/viewer.css
On my system there's no [`Verdana` font](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/d7682a655abda824c82b9d6bb7991b9576c33610/client/viewer.css#L2), therefore sidebar and tooltips are displayed with the ugly default serif font. I added an explicit `sans-serif` fallback for the `--main-font` CSS variable, to make the system use the non-serif default font, at least.
I also increased the [opacity of tooltips](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/d7682a655abda824c82b9d6bb7991b9576c33610/client/components/Tooltip.css#L8) to make them more readable against background text.
Here's a before / after:
> Improved readability: fixed serif font and tooltip opacity

- README.md
- src/BundleAnalyzerPlugin.js
- src/bin/analyzer.js
- src/viewer.js
- test/analyzer.js
- test/plugin.js
This issue can be related to https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/194.
We would like to use the statistics generated by Webpack Bundle Analyzer to track changes in projects. For that we would like to upload/save the bundle sizes in a database, and json is a lot more flexible format for that. 
I've added a test for the json output.
There is already possibility to generate html from the given json (you expose ejs file that we can directly use). But I think it would be great to add a way to generate the html from cli, but I can't think of a nice way to do it. This is what I currently have created: https://github.com/Gongreg/webpack-bundle-analyzer/pull/1/files
> Added JSON output to the cli and webpack plugin

- CHANGELOG.md
- client/components/ModulesTreemap.jsx
- client/localStorage.js
- client/store.js
- client/utils.js
As discussed in #321.
To my surprise, this works also when `{ analyzerMode: 'static' }`: I didn't know browsers save `localStorage` for local files too.
> Persisted "Show content of concatenated modules" with localStorage

- CHANGELOG.md
- src/parseUtils.js
- test/bundles/validWebpack4AsyncChunkUsingCustomGlobalObject.js
- test/bundles/validWebpack4AsyncChunkUsingCustomGlobalObject.modules.json
Issue: #350 .
Removed left hand checks, since they seem redundant. All the tests are passing. Added test case for a custom global object.
Closes #350
> Removed left side check to support custom global object which can be any string

- CHANGELOG.md
- src/parseUtils.js
- test/bundles/validWebpack4AsyncChunkWithWebWorkerChunkTemplatePlugin.js
- test/bundles/validWebpack4AsyncChunkWithWebWorkerChunkTemplatePlugin.modules.json
Issue: #351 
Added test & comment regarding the if case.
> Added support for Web worker chunk template plugin

- CHANGELOG.md
- README.md
- src/BundleAnalyzerPlugin.js
- src/bin/analyzer.js
- src/utils.js
- src/viewer.js
- test/analyzer.js
- test/plugin.js
Allows setting the HTML report title
Tests are included, they test string and function reportTitle set through the plugin API, and error propagation for the function reportTitle
I, and increasingly others, require reproducible builds with CI; this is a more specific PR targeting a single option after comments on a more general PR #349
> feat: reportTitle option (allow reproducible build)

- CHANGELOG.md
- src/utils.js
- src/viewer.js
> Catch uncaught opener errors

- CHANGELOG.md
- package-lock.json
- package.json
- src/BundleAnalyzerPlugin.js
- src/statsUtils.js
- test/statsUtils.js
This PR replaces `bfj` module with custom `StatsSerializeStream` class which writes `stats.json` significantly faster (by about 6 times). Tested on 195mb `stats.json` file.
> Replace `bfj` module with custom `stats.json` writer

- CHANGELOG.md
- src/analyzer.js
- test/analyzer.js
- test/stats/with-non-asset-asset/bundle.js
- test/stats/with-non-asset-asset/stats.json
> Fix assets without name causing analyze failure

- src/analyzer.js
- src/bin/analyzer.js
- src/parseUtils.js
- src/tree/BaseFolder.js
- src/tree/ConcatenatedModule.js
- src/tree/Folder.js
- src/utils.js
In this diff I replaced some lodash methods with native ones without
complicating code.
(Related PR: #393)
> Avoid lodash where possible

- CHANGELOG.md
- package-lock.json
- package.json
- src/template.js
- src/viewer.js
- views/script.ejs
This PR replaces the EJS based templates with a simple JS file using template strings. 
`webpack-bundle-analyzer` uses very little HTML templating since most of the client is a SPA. What is used, can be replaced by a straightforward JS file. This drops 15(!) packages from the dependencies. I also like how all functions related to generating the HTML get pulled into the same file.
> Replace ejs templates with a simple js file

- CHANGELOG.md
- client/components/Treemap.jsx
This should improve the user experience and should still be fairly smooth on recent hardware.
> Draw FoamTree labels also during animation

- .github/ISSUE_TEMPLATE.md
it throws `no matches found: --npmPackages=*webpack*` without this
> chore: quote star in issue template command

- CHANGELOG.md
- src/bin/analyzer.js
Last weak, i submit a feature about custom analyzerUrl.But i'm sorry that i'm not changed `cli mode`logic. It carsed error then use cli to start server.
refer issue: https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/523
> fix: can't setup with cli mode

- CHANGELOG.md
- package-lock.json
- package.json
- src/analyzer.js
- src/bin/analyzer.js
Node has a string size limit of 500MB and the current `JSON.parse(fs.readFileSync(...))` logic to read `stats.json` files fails for files >500MB.
This PR changes the approach for stats parsing to use a stream, similar to this PR for webpack-cli in creating the file: https://github.com/webpack/webpack-cli/pull/2190
I've tested it against a local repo with a 700MB stats.json and it works when it didn't before. I would add a test, but I don't know about adding that large of a file :joy: Could look into generating one if you would like.
> Support reading large stats.json files

- CHANGELOG.md
- client/components/Treemap.jsx
This PR reduces the saturation (from 60 to 10) for non-matches.
Note: there seems to be a bug in foamtree? It does not redraw some of the nodes until you hover over them. This seems to be a preexisting issue.
Fixes #553
<details><summary>Click to see the outdated details about the <code>.redraw()</code> behavior we've discussed in this PR</summary>
This gif shows how randomly some of the nodes are not redrawn (by foamtree) until you hover over them. I think this bug is masked by the current highlighting behavior, which does not change the color of non-matching nodes.
</details>
> feat: gray out non-matches when searching

- .github/workflows/main.yml
- CHANGELOG.md
1. Add node v16 to workflow.
2. update Github actions to v3.
> build: add node v16 & update Github actions

- CHANGELOG.md
- package-lock.json
- package.json
i'm unable to start webpack-bundle-analyzer@4.9.0 in `'server'` mode with the following traceback:
```
node_modules/webpack-bundle-analyzer/lib/viewer.js:89
sirvMiddleware(req, res);
^
TypeError: parser is not a function
at node_modules/webpack-bundle-analyzer/node_modules/sirv/build.js:163:30
at Server.<anonymous> (node_modules/webpack-bundle-analyzer/lib/viewer.js:89:7)
at Server.emit (node:events:513:28)
at Server.emit (node:domain:489:12)
at parserOnIncoming (node:_http_server:1068:12)
at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
```
it appears to be related to `sirv`, and a fix for this issue (https://github.com/lukeed/sirv/issues/124) was released in [`^2.0.0`](https://github.com/lukeed/sirv/releases/tag/v2.0.0). i've confirmed adding a resolution for this …
> bump sirv to fix analyzerMode server

- CHANGELOG.md
- client/components/Dropdown.css
- client/components/Dropdown.jsx
- client/components/ModulesTreemap.jsx
https://github.com/webpack-contrib/webpack-bundle-analyzer/discussions/622
* Allows users to filter entry points from the dropdown
<details>
<summary>Before</summary>
https://github.com/webpack-contrib/webpack-bundle-analyzer/assets/35310373/8bebb619-f6e3-4578-84e2-2d426fb3d010
</details>
<details>
<summary>After</summary>
https://github.com/webpack-contrib/webpack-bundle-analyzer/assets/35310373/ff1bb632-5dce-42af-804a-ac8c365aacad
</details>
> Allow filtering the list of entrypoints

- CHANGELOG.md
- client/components/Search.jsx
The error "this.handleValueChange.cancel is not a function" often occurs when I use webpack-bundle-analyzer, leading to a paralysis of page interaction. 
Therefore, I have made some defensive fixes in the code here. After the fixes, the generated static pages now perform normally.
> fix: handleValueChange.cancel is not a function

- package-lock.json
- package.json
- src/viewer.js
The PR removes a dependency `is-plain-object`, further reducing the installation size.
Ref #505 #609 #612
Turns out that the return value of `analyzer.getViewerData()` is always an array (from `Object.entries`), we can safely remove the `is-plain-object` guard.
> Remove `is-plain-object`

- CHANGELOG.md
- src/analyzer.js
- src/parseUtils.js
Refs #427, #556
We are now parsing bundles as ES modules based on stats JSON information
> Fixes #427, #556 use correct `sourceType` when parsing bundles

- src/viewer.js
- test/analyzer.js
See Issue [659](https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/659).
> Corrected all misspellings of the word couldn't throughout the source code.

- CHANGELOG.md
- README.md
- client/components/ModulesTreemap.jsx
- client/store.js
- src/BundleAnalyzerPlugin.js
- src/analyzer.js
- src/bin/analyzer.js
- src/sizeUtils.js
- src/template.js
- src/tree/ConcatenatedModule.js
- src/tree/ContentFolder.js
- src/tree/ContentModule.js
- src/tree/Folder.js
- src/tree/Module.js
- src/viewer.js
- test/analyzer.js
- test/plugin.js
Reimplemented #432 including feedback.
Based on `master` before #650 (see https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/650#issuecomment-2873947429) to allow for local testing.
`gzip-size` can be uninstalled. I did not include this commit b/c it creates a conflict with changes on `master` after my base.
> feat: Brotli compression support

- CHANGELOG.md
- src/analyzer.js
Thanks to Re-Pack, now even React Native projects can use Rspack or Webpack as a bundler instead of Metro.
We would like to use webpack-bundle-analyzer to discover the pain point of our app.
Unfortunately, the React Native assets are stored in a `.bundle` size: this is forcing us to patch `webpack-bundle-analyzer` to be able to use it.
With this PR, I'm going to address it.
> fix: allow react native bundle files

- src/analyzer.js
Now you can see:
```
Error parsing bundle asset "/home/alexander-akait/IdeaProjects/webpack-bundle-analyzer-reproducer-409/dist/public/index.mjs": Cannot read properties of undefined (reading 'arguments') {
cause: TypeError: Cannot read properties of undefined (reading 'arguments')
at getModulesLocations (/home/alexander-akait/IdeaProjects/webpack-bundle-analyzer-reproducer-409/node_modules/webpack-bundle-analyzer/lib/parseUtils.js:254:24)
at Object.ExpressionStatement (/home/alexander-akait/IdeaProjects/webpack-bundle-analyzer-reproducer-409/node_modules/webpack-bundle-analyzer/lib/parseUtils.js:44:35)
at c (/home/alexander-akait/IdeaProjects/webpack-bundle-analyzer-reproducer-409/node_modules/acorn-walk/dist/walk.js:58:37)
at Object.skipThrough …
```
> allow to catch parsing errors
