.travis.yml
test/webpack-configs.js
yarn.lock

Use `yarn` instead of `npm` in Travis CI

---

src/parseUtils.js
test/helpers.js
test/webpack-configs.js

Support custom value for `output.jsonpFunction` webpack config option

---

src/tree.js
test/analyzer.js
test/stats/with-invalid-dynamic-require.json

Fix `TypeError: currentFolder.addModule is not a function`

---

src/parseUtils.js
test/bundles/validExtraBundleWithNamedChunk.js
test/bundles/validExtraBundleWithNamedChunk.modules.json

This is a new feature in webpack: https://github.com/webpack/webpack/pull/4553
This PR fixes #67

Support NamedChunksPlugin

---

README.md

Resolves #61 
All thanks goes to @valscion and @th0r for helping me understand what these values mean in that issue. I just rephrased their words here.
Happy to make changes if anyone has suggestions :v:

Add stat definitions to README

---

.babelrc
README.md
client/components/ModulesTreemap.jsx
client/viewer.jsx
src/BundleAnalyzerPlugin.js
src/bin/analyzer.js
src/viewer.js
views/viewer.ejs

Add option to change default module sizes shown in report

---

client/components/CheckboxList.css
client/components/CheckboxList.jsx
client/components/CheckboxListItem.jsx
client/components/ModulesTreemap.css
client/components/ModulesTreemap.jsx
client/components/Sidebar.css
client/components/Treemap.jsx
client/utils.js

Closes #71 
Partially addresses #38

Add control to choose shown chunks

---

.babelrc
.eslintignore
client/components/CheckboxList.jsx
client/components/ModulesTreemap.jsx
client/viewer.jsx
gulpfile.babel.js
package.json
src/BundleAnalyzerPlugin.js
src/analyzer.js
src/viewer.js
test/.gitignore
webpack.config.js
yarn.lock

Adds support for `webpack --watch` mode and `webpack-dev-server`.
Analyzer now dynamically updates treemap according to changes in the sources using WebSockets.
Closes #37

Support dev modes

---

src/analyzer.js
src/parseUtils.js
src/tree.js

Greatly improve accuracy of gzip sizes

---

package.json
src/BundleAnalyzerPlugin.js
src/viewer.js
test/.gitignore
test/dev-server.js
test/dev-server/src.js
test/dev-server/tmp/.gitignore
test/dev-server/webpack.config.js

Generate report file in the bundle output directory when used with Webpack Dev Server

---

src/analyzer.js
test/helpers.js
test/webpack-configs.js

Add proper support for multi entries

---

package.json
src/parseUtils.js
test/bundles/validBundleWithEsNextFeatures.js
test/bundles/validBundleWithEsNextFeatures.modules.json
yarn.lock

Support parsing of ESNext features

---

.gitignore

This was a blooper done in 14b6356e92b6e4287bdd9fcf58b049cda1fdc716
This PR points to #97

Fix .gitignore being too eager

---

package.json
packages/reporter-treemap/package.json
packages/webpack-bundle-analyzer-plugin/package.json

Improve npm scripts

---

package.json
packages/plugin/src/BundleAnalyzerPlugin.js
packages/plugin/src/bin/analyzer.js
packages/plugin/test/analyzer.js
packages/plugin/test/dev-server.js
packages/plugin/test/dev-server/tmp/.gitignore
packages/plugin/test/dev-server/webpack.config.js
packages/plugin/test/helpers.js
packages/reporter-treemap/src/index.js
packages/reporter-treemap/src/viewer.js

I.e. the main reason version 3 will exist.
Part of #97

Add custom reporter configuration

---

client/components/CheckboxList.jsx
client/components/CheckboxListItem.jsx
client/components/ModulesTreemap.jsx
client/components/Sidebar.jsx
client/utils.js

Add chunk sizes to sidebar

---

README.md

This PR adds documentation for `ModuleConcatenationPlugin`. Closes #115

Add info about ModuleConcatenationPlugin to README.md

---

LICENSE

@th0r, you will need to be the one to merge this before we can transfer the repository to `webpack-contrib`

Update license to be compatible with webpack-contrib

---

README.md

What should I say ;-) Sorry for extra work ...

Fixed typo in angular-cli troubleshooting (#115)

---

.github/FUNDING.yml

add funding as we do on all webpack projects

docs: funding

---

CHANGELOG.md
views/viewer.ejs

fix #312 .
set `enableWebSocket` before using.

websocket does not establish under 'server' mode

---

.github/ISSUE_TEMPLATE.md

```bash
System:
OS: macOS 10.15.5
CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
Binaries:
Node: 13.11.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.5 - /usr/local/bin/npm
npmPackages:
webpack: 4.42.0 => 4.42.0 
npmGlobalPackages:
webpack-bundle-analyzer: 3.8.0
```
closes #307

[Docs]: update issue template to include the instruction to fetch local environment information

---

package-lock.json
package.json

chore: remove gzip-size dependency
